DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH (
BRANCH_ID INT AUTO_INCREMENT  PRIMARY KEY,
BRANCH_NAME VARCHAR(50) NOT NULL,
BRANCH_LOCATION VARCHAR(250) NOT NULL);

DROP TABLE IF EXISTS INTEREST;
CREATE TABLE INTEREST (
INTEREST_ID INT AUTO_INCREMENT  PRIMARY KEY,
INTEREST_TYPE VARCHAR(50) NOT NULL,
INTEREST_VALUE INT NOT NULL);


DROP TABLE IF EXISTS ACCOUNT_TYPE;
CREATE TABLE ACCOUNT_TYPE (
ACCOUNT_TYPE_ID INT AUTO_INCREMENT  PRIMARY KEY,
ACCOUNT_TYPE_NAME VARCHAR(50) NOT NULL,
INTEREST_ID INT NOT NULL);

DROP TABLE IF EXISTS USER_DETAILS;
CREATE TABLE USER_DETAILS (
USER_ID INT AUTO_INCREMENT  PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
MIDDLE_NAME VARCHAR(50) ,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE VARCHAR(50) NOT NULL,
ADDRESS VARCHAR(300) NOT NULL,
SECURITY_NUMBER VARCHAR(300) NOT NULL);


DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
USER_ID NUMERIC NOT NULL,
ACCOUNT_NUMBER NUMERIC AUTO_INCREMENT ,
ACCOUNT_TYPE_ID NUMERIC NOT NULL,
BRANCH_ID NUMERIC NOT NULL,
ACCOUNT_HOLDER_NAME VARCHAR(250) NOT NULL,
BALANCE DOUBLE NOT NULL,
STATUS VARCHAR(10) NOT NULL);